"""
FastAPI application for the document processing pipeline.

The upload endpoint stores a file on disk, records it in the database with
status "pending", and queues an ARQ job in Redis. A separate worker process
does the heavy lifting and updates the document status; clients poll the API
to observe progress and read the resulting chunks.
"""

from contextlib import asynccontextmanager
from pathlib import Path
from uuid import uuid4

import aiofiles

from redis_queue import create_redis_pool

from fastapi import (
    Depends,
    FastAPI,
    Request,
    File,
    HTTPException,
    UploadFile,
)
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from database import engine, get_db
from models import Document, DocumentChunk
from processing_service import process_document
from schemas import (
    DocumentCreate,
    DocumentResponse,
    DocumentUpdate,
    DocumentChunkResponse,
)


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Open a shared Redis pool on startup and release it on shutdown."""

    app.state.redis = await create_redis_pool()

    yield

    await app.state.redis.aclose()
    await engine.dispose()

app = FastAPI(lifespan=lifespan)


@app.get("/")
async def home():
    """Simple health/hello endpoint."""

    return {"message": "Document Processing API"}


@app.post("/documents", response_model=DocumentResponse)
async def create_document(
    document: DocumentCreate, #validated request data
    db: AsyncSession = Depends(get_db), # FastAPI automatically gives endpoint a database session.
):
    """Create a metadata-only document record (no file, no processing job)."""

    #takes data from the Pydantic schema and creates a SQLAlchemy model.
    new_document = Document(
        filename=document.filename,
        file_path=f"uploads/{document.filename}",
        content_type="application/octet-stream",
        file_size=0,
    )

    db.add(new_document)

    await db.commit()
    await db.refresh(new_document) #refreshes the object with values generated by the database, such as its id.

    return new_document

@app.get("/documents", response_model=list[DocumentResponse])
async def get_documents(
    db: AsyncSession = Depends(get_db),
):
    """Return every document in the database."""

    result = await db.execute(
        select(Document)
    )

    documents = result.scalars().all()

    return documents

@app.get("/documents/{doc_id}", response_model=DocumentResponse)
async def get_document(
    doc_id: int,
    db: AsyncSession = Depends(get_db),
):
    """Return a single document by id, or 404 if it does not exist."""

    result = await db.execute(
        select(Document).where(Document.id == doc_id)
    )

    document = result.scalar_one_or_none()

    if document is None:
        raise HTTPException(
            status_code=404,
            detail="Document not found"
        )

    return document


@app.patch(
    "/documents/{doc_id}",
    response_model=DocumentResponse,
)
async def update_document(
    doc_id: int,
    document_data: DocumentUpdate,
    db: AsyncSession = Depends(get_db),
):
    """Apply a partial update to a document and return the updated record."""

    result = await db.execute(
        select(Document).where(Document.id == doc_id)
    )

    document = result.scalar_one_or_none()

    if document is None:
        raise HTTPException(
            status_code=404,
            detail="Document not found",
        )

    # Only the fields the client actually sent.
    update_data = document_data.model_dump(exclude_unset=True)

    for field, value in update_data.items():
        setattr(document, field, value)

    await db.commit()
    await db.refresh(document)

    return document


@app.delete("/documents/{doc_id}", status_code=204)
async def delete_document(
    doc_id: int,
    db: AsyncSession = Depends(get_db),
):
    """Delete a document by id."""

    result = await db.execute(
        select(Document).where(Document.id == doc_id)
    )

    document = result.scalar_one_or_none()

    if document is None:
        raise HTTPException(
            status_code=404,
            detail="Document not found",
        )

    await db.delete(document)
    await db.commit()


UPLOAD_DIR = Path("uploads")
UPLOAD_DIR.mkdir(exist_ok=True)

# File types the upload endpoint accepts.
ALLOWED_EXTENSIONS = {".pdf", ".docx"}

ALLOWED_CONTENT_TYPES = {
    "application/pdf",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
}

@app.post(
    "/documents/upload",
    response_model=DocumentResponse,
    status_code=202,
)
async def upload_document(
    request: Request,
    file: UploadFile = File(...),
    db: AsyncSession = Depends(get_db),
):
    """
    Validate and store an uploaded file, then queue it for processing.

    Returns 202 Accepted immediately; the ARQ worker processes the file
    asynchronously and updates the document's status.
    """

    if not file.filename:
        raise HTTPException(
            status_code=400,
            detail="Filename is missing",
        )

    # Strip any directory components to prevent path traversal.
    original_filename = Path(file.filename).name
    extension = Path(original_filename).suffix.lower()

    if extension not in ALLOWED_EXTENSIONS:
        raise HTTPException(
            status_code=400,
            detail="Only PDF and DOCX files are allowed",
        )

    content_type = file.content_type

    if content_type not in ALLOWED_CONTENT_TYPES:
        raise HTTPException(
            status_code=400,
            detail="Unsupported file type",
        )

    # Store under a random name to avoid collisions.
    stored_filename = f"{uuid4().hex}{extension}"
    file_path = UPLOAD_DIR / stored_filename

    file_size = 0

    try:
        # Save the uploaded file.
        async with aiofiles.open(
            file_path,
            "wb",
        ) as output_file:

            # Stream in 1 MiB blocks so large files stay out of memory.
            while chunk := await file.read(1024 * 1024):
                file_size += len(chunk)
                await output_file.write(chunk)

        # Create the document record.
        new_document = Document(
            filename=original_filename,
            file_path=file_path.as_posix(),
            content_type=content_type,
            file_size=file_size,
            status="pending",
        )

        db.add(new_document)

        # Get the database-generated document ID.
        await db.flush()

        # Save the document.
        await db.commit()

        await db.refresh(new_document)

        # Put the processing job into Redis.
        redis = request.app.state.redis

        job = await redis.enqueue_job(
            "process_document_job",
            new_document.id,
        )

        if job is None:
            raise RuntimeError(
                "Document processing job could not be queued"
            )

        # Return immediately.
        return new_document

    except Exception:
        # Undo uncommitted database work and remove the stored file.
        await db.rollback()

        if file_path.exists():
            file_path.unlink()

        raise

    finally:
        await file.close()

@app.get(
    "/documents/{doc_id}/chunks",
    response_model=list[DocumentChunkResponse],
)
async def get_document_chunks(
    doc_id: int,
    db: AsyncSession = Depends(get_db),
):
    """Return all text chunks of a document, ordered by their index."""

    # First check that the document exists
    document_result = await db.execute(
        select(Document).where(Document.id == doc_id)
    )

    document = document_result.scalar_one_or_none()

    if document is None:
        raise HTTPException(
            status_code=404,
            detail="Document not found",
        )

    # Get all chunks belonging to this document
    result = await db.execute(
        select(DocumentChunk)
        .where(DocumentChunk.document_id == doc_id)
        .order_by(DocumentChunk.chunk_index)
    )

    chunks = result.scalars().all()

    return chunks
