from contextlib import asynccontextmanager

from fastapi import Depends, FastAPI
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from database import Base, engine, get_db
from models import Document
from schemas import DocumentCreate, DocumentResponse


@asynccontextmanager
async def lifespan(app: FastAPI):
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    yield

    await engine.dispose()


app = FastAPI(lifespan=lifespan)


@app.get("/")
async def home():
    return {"message": "Document Processing API"}


@app.post("/documents", response_model=DocumentResponse)
async def create_document(
    document: DocumentCreate, #validated request data
    db: AsyncSession = Depends(get_db), # FastAPI automatically gives endpoint a database session.
):
    #takes data from the Pydantic schema and creates a SQLAlchemy model.
    new_document = Document(
        filename=document.filename
    )

    db.add(new_document)

    await db.commit()
    await db.refresh(new_document) #refreshes the object with values generated by the database, such as its id.

    return new_document