from contextlib import asynccontextmanager

from uuid import uuid4



from pathlib import Path
from chunks import chunk_text
from text_cleaner import clean_text

import aiofiles
import asyncio
from extractor import extract_text

from fastapi import Depends, FastAPI, HTTPException, File, UploadFile
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from database import Base, engine, get_db
from models import Document, DocumentChunk
from schemas import DocumentCreate, DocumentResponse, DocumentUpdate, DocumentChunkResponse


@asynccontextmanager
async def lifespan(app: FastAPI):
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    yield

    await engine.dispose()


app = FastAPI(lifespan=lifespan)


@app.get("/")
async def home():
    return {"message": "Document Processing API"}


@app.post("/documents", response_model=DocumentResponse)
async def create_document(
    document: DocumentCreate, #validated request data
    db: AsyncSession = Depends(get_db), # FastAPI automatically gives endpoint a database session.
):
    #takes data from the Pydantic schema and creates a SQLAlchemy model.
    new_document = Document(
        filename=document.filename,
        file_path=f"uploads/{document.filename}",
        content_type="application/octet-stream",
        file_size=0,
    )

    db.add(new_document)

    await db.commit()
    await db.refresh(new_document) #refreshes the object with values generated by the database, such as its id.

    return new_document

@app.get("/documents", response_model=list[DocumentResponse])
async def get_documents(
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(Document)
    )

    documents = result.scalars().all()

    return documents

@app.get("/documents/{doc_id}", response_model=DocumentResponse)
async def get_document(
    doc_id: int,
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(Document).where(Document.id == doc_id)
    )

    document = result.scalar_one_or_none()

    if document is None:
        raise HTTPException(
            status_code=404,
            detail="Document not found"
        )

    return document


@app.patch(
    "/documents/{doc_id}",
    response_model=DocumentResponse,
)
async def update_document(
    doc_id: int,
    document_data: DocumentUpdate,
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(Document).where(Document.id == doc_id)
    )

    document = result.scalar_one_or_none()

    if document is None:
        raise HTTPException(
            status_code=404,
            detail="Document not found",
        )

    update_data = document_data.model_dump(exclude_unset=True)

    for field, value in update_data.items():
        setattr(document, field, value)

    await db.commit()
    await db.refresh(document)

    return document


@app.delete("/documents/{doc_id}", status_code=204)
async def delete_document(
    doc_id: int,
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(Document).where(Document.id == doc_id)
    )

    document = result.scalar_one_or_none()

    if document is None:
        raise HTTPException(
            status_code=404,
            detail="Document not found",
        )

    await db.delete(document)
    await db.commit()


UPLOAD_DIR = Path("uploads")
UPLOAD_DIR.mkdir(exist_ok=True)

ALLOWED_EXTENSIONS = {".pdf", ".docx"}

ALLOWED_CONTENT_TYPES = {
    "application/pdf",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
}


@app.post(
    "/documents/upload",
    response_model=DocumentResponse,
    status_code=201,
)
async def upload_document(
    file: UploadFile = File(...),
    db: AsyncSession = Depends(get_db),
):
    if not file.filename:
        raise HTTPException(
            status_code=400,
            detail="Filename is missing",
        )

    original_filename = Path(file.filename).name
    extension = Path(original_filename).suffix.lower()

    if extension not in ALLOWED_EXTENSIONS:
        raise HTTPException(
            status_code=400,
            detail="Only PDF and DOCX files are allowed",
        )

    content_type = file.content_type

    if content_type not in ALLOWED_CONTENT_TYPES:
        raise HTTPException(
            status_code=400,
            detail="Unsupported file type",
        )

    stored_filename = f"{uuid4().hex}{extension}"
    file_path = UPLOAD_DIR / stored_filename

    file_size = 0

    try:
        # 1. Save the file
        async with aiofiles.open(
            file_path,
            "wb",
        ) as output_file:

            while chunk := await file.read(1024 * 1024):
                file_size += len(chunk)
                await output_file.write(chunk)

        # 2. Extract text
        text = await asyncio.to_thread(
            extract_text,
            file_path,
        )

        # 3. Clean text
        text = clean_text(text)

        # 4. Create chunks
        chunks = chunk_text(text)

        # 5. Create document
        new_document = Document(
            filename=original_filename,
            file_path=file_path.as_posix(),
            content_type=content_type,
            file_size=file_size,
            extracted_text=text,
        )

        db.add(new_document)

        # Get database-generated ID
        await db.flush()

        # 6. Create chunk records
        chunk_objects = []

        for index, chunk in enumerate(chunks):
            chunk_object = DocumentChunk(
                document_id=new_document.id,
                chunk_index=index,
                content=chunk,
            )

            chunk_objects.append(chunk_object)

        # 7. Add chunks to session
        db.add_all(chunk_objects)

        # 8. Commit document + chunks
        await db.commit()

        # 9. Refresh document
        await db.refresh(new_document)

        return new_document

    except Exception:
        await db.rollback()

        if file_path.exists():
            file_path.unlink()

        raise

    finally:
        await file.close()


@app.get(
    "/documents/{doc_id}/chunks",
    response_model=list[DocumentChunkResponse],
)
async def get_document_chunks(
    doc_id: int,
    db: AsyncSession = Depends(get_db),
):
    # First check that the document exists
    document_result = await db.execute(
        select(Document).where(Document.id == doc_id)
    )

    document = document_result.scalar_one_or_none()

    if document is None:
        raise HTTPException(
            status_code=404,
            detail="Document not found",
        )

    # Get all chunks belonging to this document
    result = await db.execute(
        select(DocumentChunk)
        .where(DocumentChunk.document_id == doc_id)
        .order_by(DocumentChunk.chunk_index)
    )

    chunks = result.scalars().all()

    return chunks