from contextlib import asynccontextmanager

from pathlib import Path
import aiofiles


from fastapi import Depends, FastAPI, HTTPException, File, UploadFile
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from database import Base, engine, get_db
from models import Document
from schemas import DocumentCreate, DocumentResponse, DocumentUpdate


@asynccontextmanager
async def lifespan(app: FastAPI):
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    yield

    await engine.dispose()


app = FastAPI(lifespan=lifespan)


@app.get("/")
async def home():
    return {"message": "Document Processing API"}


@app.post("/documents", response_model=DocumentResponse)
async def create_document(
    document: DocumentCreate, #validated request data
    db: AsyncSession = Depends(get_db), # FastAPI automatically gives endpoint a database session.
):
    #takes data from the Pydantic schema and creates a SQLAlchemy model.
    new_document = Document(
        filename=document.filename,
        file_path=f"uploads/{document.filename}",
        content_type="application/octet-stream",
        file_size=0,
    )

    db.add(new_document)

    await db.commit()
    await db.refresh(new_document) #refreshes the object with values generated by the database, such as its id.

    return new_document

@app.get("/documents", response_model=list[DocumentResponse])
async def get_documents(
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(Document)
    )

    documents = result.scalars().all()

    return documents

@app.get("/documents/{doc_id}", response_model=DocumentResponse)
async def get_document(
    doc_id: int,
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(Document).where(Document.id == doc_id)
    )

    document = result.scalar_one_or_none()

    if document is None:
        raise HTTPException(
            status_code=404,
            detail="Document not found"
        )

    return document


@app.patch(
    "/documents/{doc_id}",
    response_model=DocumentResponse,
)
async def update_document(
    doc_id: int,
    document_data: DocumentUpdate,
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(Document).where(Document.id == doc_id)
    )

    document = result.scalar_one_or_none()

    if document is None:
        raise HTTPException(
            status_code=404,
            detail="Document not found",
        )

    update_data = document_data.model_dump(exclude_unset=True)

    for field, value in update_data.items():
        setattr(document, field, value)

    await db.commit()
    await db.refresh(document)

    return document


@app.delete("/documents/{doc_id}", status_code=204)
async def delete_document(
    doc_id: int,
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(Document).where(Document.id == doc_id)
    )

    document = result.scalar_one_or_none()

    if document is None:
        raise HTTPException(
            status_code=404,
            detail="Document not found",
        )

    await db.delete(document)
    await db.commit()


UPLOAD_DIR = Path("uploads")
UPLOAD_DIR.mkdir(exist_ok=True)

ALLOWED_EXTENSIONS = {".pdf", ".docx"}

ALLOWED_CONTENT_TYPES = {
    "application/pdf",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
}


@app.post("/documents/upload",
          response_model=DocumentResponse,
          status_code=201,
)

async def upload_document(
    file: UploadFile = File(...),
    db: AsyncSession = Depends(get_db),
):
    if not file.filename:
        raise HTTPException(
            status_code=400,
            detail="Filename is missing",
        )

    filename = Path(file.filename).name
    extension = Path(filename).suffix.lower()

    if extension not in ALLOWED_EXTENSIONS:
        raise HTTPException(
            status_code=400,
            detail="Only PDF and DOCX files are allowed",
        )

    if file.content_type not in ALLOWED_CONTENT_TYPES:
        raise HTTPException(
            status_code=400,
            detail="Unsupported file type",
        )

    file_path = UPLOAD_DIR / filename

    try:
        # Save actual file
        file_size = 0

        async with aiofiles.open(file_path, "wb") as output_file:
            while chunk := await file.read(1024 * 1024):
                file_size += len(chunk)
                await output_file.write(chunk)

        # Create database record
        new_document = Document(
            filename=filename,
            file_path=str(file_path),
            content_type=file.content_type,
            file_size=file_size
        
        )

        db.add(new_document)

        # Save database changes
        await db.commit()

        # Get generated values such as ID
        await db.refresh(new_document)

        return new_document

    except Exception:
        # Undo database transaction
        await db.rollback()

        # Delete file if it was already saved
        if file_path.exists():
            file_path.unlink()

        raise

    finally:
        await file.close()